lib/story_web/router.ex
defmodule StoryWeb.Router do
  use StoryWeb, :router
  use Honeybadger.Plug

  import StoryWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {StoryWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json", "html"]

  end

  scope "/", StoryWeb do
    pipe_through :browser

    get "/", PageController, :index
    get "/:slug", PageController, :show
    get "/cv/:slug", PageController, :cv
  end

  # Other scopes may use custom stacks.
   scope "/api", StoryWeb do
     pipe_through :api

      get "/stories/to_json", API.ExportsController, :json
   end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: StoryWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end

  ## Authentication routes


   scope "/auth", StoryWeb do
      pipe_through [:browser, :redirect_if_user_is_authenticated]

      get "/:provider", OAuthController, :request
      get "/:provider/callback", OAuthController, :callback
      post "/:provider/callback", OAuthController, :callback
      delete "/logout", OAuthController, :delete
    end

  scope "/", StoryWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    get "/users/log_in_from_preview", UserSessionController, :create_from_preview
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update

    live "/users/story/preview", PreviewLive
  end

  scope "/", StoryWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/users/settings", UserSettingsController, :edit
    put "/users/settings", UserSettingsController, :update
    delete "/users/settings", UserSettingsController, :destroy_user
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email

    live "/users/story/import", ImportLive
    live "/users/story/edit", EditLive
    live "/users/story/new", NewLive
  end

  scope "/", StoryWeb do
    pipe_through [:browser]

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :edit
    post "/users/confirm/:token", UserConfirmationController, :update
  end
end

lib/story_web/controllers/user_session_controller.ex
defmodule StoryWeb.UserSessionController do
  use StoryWeb, :controller

  alias Story.Accounts
  alias StoryWeb.UserAuth

  def new(conn, _params) do
    render(conn, "new.html", error_message: nil)
  end

  def create_from_preview(conn, params) do
    %{"so_url" => so_url} = params

    conn
    |> put_session(:user_return_to, Routes.live_path(conn, StoryWeb.ImportLive, %{so_url: so_url}))
    |> create(params)
  end

  def create(conn, %{"user" => user_params}) do
    %{"email" => email, "password" => password} = user_params

    if user = Accounts.get_user_by_email_and_password(email, password) do
      UserAuth.log_in_user(conn, user, user_params)
    else
      # In order to prevent user enumeration attacks, don't disclose whether the email is registered.
      render(conn, "new.html", error_message: "Invalid email or password")
    end
  end

  def delete(conn, _params) do
    conn
    |> put_flash(:info, "Logged out successfully.")
    |> UserAuth.log_out_user()
  end
end

lib/story_web/views/user_session_view.ex
defmodule StoryWeb.UserSessionView do
  use StoryWeb, :view
end

lib/story_web/templates/user_session/new.html.heex
<div class="min-h-screen w-full mt-12 px-8 lg:px-0">
  <div class="lg:w-1/3 mx-auto">
    <.form let={f} for={@conn} action={Routes.user_session_path(@conn, :create)} as={:user}>
      <div class="p-10 card bg-base-100 border shadow-md border-base-300 mb-8">

        <p class="text-neutral mb-1">Log in with:</p>

        <%= link to: Routes.o_auth_path(@conn, :request, "github"), class: "btn btn-outline btn-neutral btn-block mx-auto gap-2" do %>
          <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" class="h-6 w-6" viewBox="0 0 16 16">
            <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.012 8.012 0 0 0 16 8c0-4.42-3.58-8-8-8z"></path>
          </svg>
          GitHub
        <% end %>

        <div class="divider text-neutral my-8 border-opacity-10">or continue with</div>

        <%= if @error_message do %>
          <div class="alert alert-error">
            <div class="flex-1">
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" class="w-6 h-6 mx-2 stroke-current">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M18.364 18.364A9 9 0 005.636 5.636m12.728 12.728A9 9 0 015.636 5.636m12.728 12.728L5.636 5.636"></path>
              </svg>
              <label><%= @error_message %></label>
            </div>
          </div>
        <% end %>

        <div class="form-control mb-8">
          <%= label f, :email, class: "label" do %>
            <span class="label-text font-bold">Email</span>
          <% end %>
          <%= email_input f, :email, required: true, class: "input input-bordered" %>
        </div>

        <div class="form-control mb-8">
          <%= label f, :password, class: "label" do %>
            <span class="label-text font-bold">Password</span>
          <% end %>
          <%= password_input f, :password, required: true, class: "input input-bordered" %>
        </div>

        <div class="form-control mb-8 w-36">
          <%= label f, :remember_me, class: "cursor-pointer label" do %>
            <%= checkbox f, :remember_me, class: "checkbox checkbox-primary" %>
            <span class="label-text font-bold">Remember me</span>
          <% end %>
        </div>

        <div>
          <%= submit "Log in", class: "btn btn-block btn-primary" %>
        </div>
        <p class="mt-4 text-center">
          <%= link "Register", to: Routes.user_registration_path(@conn, :new), class: "link link-primary" %> •
          <%= link "Forgot your password?", to: Routes.user_reset_password_path(@conn, :new), class: "link link-primary" %>
        </p>
      </div>
    </.form>
  </div>
</div>